spring.application.name=Reservas-MS-Auth-Service
spring.config.import=optional:file:.env
spring.profiles.active=${SPRING_PROFILE:dev}

# Content Negotiation
spring.mvc.contentnegotiation.favor-path-extension=false
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.media-types.json=application/json

# JWT Configuration
jwt.secret=${JWT_SECRET:default-secret-key-change-in-prod}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Logging base
logging.level.com.codefactory.reservasmsauthservice=DEBUG
logging.level.org.springframework.web=INFO